-- Find the model number and price of all PCs and Laptops made by manufacturer ‘B’
SELECT MODEL , PRICE
FROM PRODUCT NATURAL JOIN PC
WHERE MAKER = 'B'
UNION
SELECT MODEL , PRICE
FROM PRODUCT NATURAL JOIN LAPTOP
WHERE MAKER = 'B';

-- Find those manufacturers that sell both PCs and Laptops
SELECT MAKER
FROM PRODUCT NATURAL JOIN PC
INTERSECT
SELECT MAKER
FROM PRODUCT NATURAL JOIN LAPTOP;

-- Find those manufacturers that sell Laptops, but not PCs
SELECT DISTINCT MAKER 
FROM PRODUCT NATURAL JOIN LAPTOP
MINUS
SELECT DISTINCT MAKER 
FROM PRODUCT NATURAL JOIN PC;