SELECT (E.FIRST_NAME||' '||E.LAST_NAME) FULLNAME,M.LAST_NAME MANAGER
FROM EMPLOYEES E JOIN EMPLOYEES M 
ON (E.MANAGER_ID = M.MANAGER_ID);

SELECT E.LAST_NAME, E.SALARY, J.GRADE_LEVEL 
FROM EMPLOYEES E JOIN JOB_GRADES J
ON (E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL) ;

SELECT (E1.FIRST_NAME||' '||E1.LAST_NAME) FULLNAME,COUNT(DISTINCT E2.EMPLOYEE_ID) HIGHSAL
FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2
ON E2.SALARY > E1.SALARY
GROUP BY E1.EMPLOYEE_ID,(E1.FIRST_NAME||' '||E1.LAST_NAME)
ORDER BY HIGHSAL,(E1.FIRST_NAME||' '||E1.LAST_NAME);

SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY FROM EMPLOYEES E JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID) JOIN LOCATIONS L
ON (D.LOCATION_ID = L.LOCATION_ID) ;

SELECT E1.LAST_NAME, COUNT(*) TOTAL FROM EMPLOYEES E1 LEFT OUTER JOIN EMPLOYEES E2 ON (E1.EMPLOYEE_ID = E2.MANAGER_ID) GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
ORDER BY TOTAL ASC ;

SELECT DEPARTMENT_NAME,COUNTRY_NAME
FROM DEPARTMENTS JOIN LOCATIONS USING (LOCATION_ID)
JOIN COUNTRIES USING (COUNTRY_ID);

SELECT COUNTRY_NAME,COUNT(DEPARTMENT_ID)
FROM COUNTRIES JOIN LOCATIONS USING(COUNTRY_ID) 
JOIN DEPARTMENTS USING(LOCATION_ID)
GROUP BY COUNTRY_ID,COUNTRY_NAME;

SELECT DEPARTMENT_NAME,JOB_TITLE,COUNT(*)
FROM DEPARTMENTS JOIN EMPLOYEES USING(DEPARTMENT_ID)
JOIN JOBS USING(JOB_ID)
GROUP BY DEPARTMENT_NAME,JOB_TITLE;

SELECT
	E1.LAST_NAME,
	COUNT(DISTINCT E2.EMPLOYEE_ID )  TOTAL_EMPLOYEES_HIRED_BEFORE,
	COUNT(DISTINCT E3.EMPLOYEE_ID )  TOTAL_EMPLOYEES_HIRED_AFTER
FROM
	EMPLOYEES E1
	LEFT OUTER JOIN EMPLOYEES E2 ON ( E2.HIRE_DATE < E1.HIRE_DATE ) 
	LEFT OUTER JOIN EMPLOYEES E3 ON ( E3.HIRE_DATE > E1.HIRE_DATE ) 
GROUP BY
	E1.LAST_NAME
-- 	E1.EMPLOYEE_ID
	ORDER BY
	TOTAL_EMPLOYEES_HIRED_BEFORE;


SELECT
	E1.EMPLOYEE_ID,
	COUNT( DISTINCT E2.EMPLOYEE_ID ) NUM 
FROM
	EMPLOYEES E1
	JOIN EMPLOYEES E2 ON E1.SALARY >= E2.SALARY 
GROUP BY
	E1.EMPLOYEE_ID 
HAVING
	COUNT( DISTINCT E2.EMPLOYEE_ID ) >= 3 
ORDER BY
	E1.EMPLOYEE_ID;

SELECT
	E1.LAST_NAME,
	E1.SALARY,
	COUNT( DISTINCT E2.SALARY ) + 1 RANK 
FROM
	EMPLOYEES E1
	LEFT JOIN EMPLOYEES E2 ON E2.SALARY > E1.SALARY 
GROUP BY
	E1.SALARY,
	E1.LAST_NAME 
ORDER BY
	RANK;

SELECT
	E1.LAST_NAME,
	E1.SALARY,
	COUNT( DISTINCT E2.SALARY ) + 1 RANK 
FROM
	EMPLOYEES E1
	LEFT JOIN EMPLOYEES E2 ON E2.SALARY > E1.SALARY 
GROUP BY
-- 	E1.EMPLOYEE_ID,
	E1.SALARY,
	E1.LAST_NAME 
HAVING
	COUNT( DISTINCT E2.SALARY ) + 1 <= 3 
ORDER BY
	RANK;


