
-- MORE THAN 2
SELECT
	D.DEPARTMENT_NAME,
	R.REGION_NAME 
FROM
	DEPARTMENTS D
	JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
	JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
	JOIN REGIONS R ON C.REGION_ID = R.REGION_ID;
SELECT
	M.LAST_NAME MANAGER,
	COUNT( E.EMPLOYEE_ID ) EMPLOYEE 
FROM
	EMPLOYEES M LEFT OUTER
	JOIN EMPLOYEES E ON M.EMPLOYEE_ID = E.MANAGER_ID 
GROUP BY
	M.EMPLOYEE_ID,
	M.LAST_NAME 
ORDER BY
	M.LAST_NAME;
	
	
SELECT
	E1.EMPLOYEE_ID EMPLOYEE,
	E1.FIRST_NAME||' '||E1.LAST_NAME NAME,
	COUNT( E2.SALARY ) SALARY_HIGHER_THAN
FROM
	EMPLOYEES E1
	JOIN EMPLOYEES E2 ON E1.SALARY > E2.SALARY 
GROUP BY
	E1.EMPLOYEE_ID,
	E1.FIRST_NAME||' '||E1.LAST_NAME 
HAVING
	COUNT( E2.SALARY ) >= 3
ORDER BY 
	SALARY_HIGHER_THAN DESC;
-- SUB QUERY

	
	
	

	
	
SELECT
	E.LAST_NAME,
	E.SALARY 
FROM
	EMPLOYEES E 
WHERE
	JOB_ID <> 'IT_PROG' 
	AND SALARY > ( SELECT MIN( SALARY ) FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' );
	
	
SELECT
	* 
FROM
	EMPLOYEES E1 
WHERE
	3 <= ( SELECT COUNT( * ) FROM EMPLOYEES E2 WHERE E2.SALARY < E1.SALARY );
SELECT
	DEPARTMENT_NAME 
FROM
	DEPARTMENTS D 
WHERE
	NOT EXISTS ( SELECT * FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND JOB_ID = 'IT_PROG' );
	
	
SELECT
	LAST_NAME,
	SALARY,
	( SELECT D.DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID = E1.DEPARTMENT_ID ) DEPARTMENT 
FROM
	EMPLOYEES E1 
WHERE
	NOT EXISTS ( SELECT * FROM EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E1.DEPARTMENT_ID AND E2.SALARY > E1.SALARY );
	
	
	
SELECT
	E1.LAST_NAME,
	E1.SALARY,
	MIN( E2.LAST_NAME ),
	MIN( E2.SALARY ) 
FROM
	EMPLOYEES E1
	JOIN EMPLOYEES E2 ON E1.DEPARTMENT_ID = E2.DEPARTMENT_ID 
GROUP BY
	E1.EMPLOYEE_ID,
	E1.LAST_NAME,
	E1.SALARY 
ORDER BY
	E1.LAST_NAME;
	
	
SELECT
	E1.LAST_NAME,
	E1.SALARY,
	D.MINSAL,
	D.MAXSAL 
FROM
	EMPLOYEES E1,
	( SELECT DEPARTMENT_ID AS DEPT, MIN( SALARY ) MINSAL, MAX( SALARY ) MAXSAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID ) D 
WHERE
	( E1.DEPARTMENT_ID = D.DEPT ) 
ORDER BY
	E1.SALARY;
	
	
	

	


SELECT
	EMPLOYEE_ID,
	FIRST_NAME || ' ' || LAST_NAME FULLNAME,
	SALARY 
FROM 
	EMPLOYEES
WHERE
	JOB_ID <> 'IT_PROG'
	AND
	SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG')
ORDER BY 
	EMPLOYEE_ID;
	
SELECT
	EMPLOYEE_ID,
	FIRST_NAME || ' ' || LAST_NAME FULLNAME,
	SALARY 
FROM
	EMPLOYEES 
WHERE
	SALARY > ALL ( SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = ( SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales' ) ) 
ORDER BY
	EMPLOYEE_ID;
	
	
SELECT
	EMPLOYEE_ID,
	FIRST_NAME || ' ' || LAST_NAME FULLNAME,
	SALARY 
FROM
	EMPLOYEES 
WHERE
	SALARY BETWEEN (( SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = ( SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales' ) ) -5000) AND
	(( SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = ( SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales' ) ) +5000)
ORDER BY
	EMPLOYEE_ID;
	
SELECT 
	E1.EMPLOYEE_ID,
	E1.FIRST_NAME || ' ' || E1.LAST_NAME FULLNAME,
	E1.SALARY 
FROM
	EMPLOYEES E1
WHERE (SELECT COUNT(*) FROM EMPLOYEES E2 WHERE E2.SALARY < E1.SALARY) >=3;

SELECT 
	E1.EMPLOYEE_ID,
	E1.FIRST_NAME || ' ' || E1.LAST_NAME FULLNAME,
	E1.SALARY,
	COUNT(DISTINCT E2.EMPLOYEE_ID)  NUM
FROM 
	EMPLOYEES E1 JOIN EMPLOYEES E2
ON	
	E1.SALARY > E2.SALARY
GROUP BY
	E1.EMPLOYEE_ID,
	(E1.FIRST_NAME || ' ' || E1.LAST_NAME),
	E1.SALARY 
HAVING 
	COUNT(DISTINCT E2.EMPLOYEE_ID) >=3
ORDER BY
	E1.EMPLOYEE_ID;

SELECT
	DEPARTMENT_NAME 
FROM
	DEPARTMENTS D 
WHERE
	EXISTS ( SELECT * FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND JOB_ID = 'IT_PROG' );

SELECT
	E1.EMPLOYEE_ID,
	E1.FIRST_NAME || ' ' || E1.LAST_NAME FULLNAME,
	E1.SALARY,
	( SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = E1.DEPARTMENT_ID ) DEPARTMENT_NAME 
FROM
	EMPLOYEES E1 
WHERE
	NOT EXISTS ( SELECT * FROM EMPLOYEES E2 WHERE E2.SALARY > E1.SALARY AND E2.DEPARTMENT_ID = E1.DEPARTMENT_ID ) 
	AND E1.DEPARTMENT_ID IS NOT NULL 
ORDER BY
	E1.DEPARTMENT_ID;


SELECT 
	E1.EMPLOYEE_ID,
	E1.FIRST_NAME || ' ' || E1.LAST_NAME FULLNAME,
	E1.SALARY,
	MIN(E2.SALARY) MIN_DEPT_SAL,
	MAX(E2.SALARY) MAX_DEPT_SAL
FROM
	EMPLOYEES E1 JOIN EMPLOYEES E2
ON 
	E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
GROUP BY
	E1.EMPLOYEE_ID,
	E1.FIRST_NAME || ' ' || E1.LAST_NAME,
	E1.SALARY
ORDER BY
	E1.EMPLOYEE_ID;
	
	
SELECT
	E1.EMPLOYEE_ID,
	E1.FIRST_NAME || ' ' || E1.LAST_NAME FULLNAME,
	E1.SALARY,
	(SELECT MIN(E2.SALARY) FROM EMPLOYEES E2 WHERE E1.DEPARTMENT_ID = E2.DEPARTMENT_ID) MIN_DEPT_SAL,
	(SELECT MAX(E2.SALARY) FROM EMPLOYEES E2 WHERE E1.DEPARTMENT_ID = E2.DEPARTMENT_ID) MAX_DEPT_SAL
FROM 
		EMPLOYEES E1
ORDER BY
	E1.EMPLOYEE_ID;
	
SELECT
	E.LAST_NAME,
	E.SALARY,
	D.MINSAL,
	D.MAXSAL 
FROM
	EMPLOYEES E,
	( SELECT DEPARTMENT_ID AS DEPT, MIN( SALARY ) MINSAL, MAX( SALARY ) MAXSAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID ) D 
WHERE
	( E.DEPARTMENT_ID = D.DEPT ) 
ORDER BY
	E.SALARY;


SELECT
	D1.DEPARTMENT_NAME
FROM
	DEPARTMENTS D1
WHERE
	(SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = D1.DEPARTMENT_ID)
	> ALL(SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID <> D1.DEPARTMENT_ID GROUP BY DEPARTMENT_ID);


SELECT
	E.DEPARTMENT_ID,
	( SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE E.DEPARTMENT_ID = DEPARTMENT_ID ) DEPARTMENT_NAME,
	COUNT( E.EMPLOYEE_ID ) NUM 
FROM
	EMPLOYEES E 
WHERE
	E.EMPLOYEE_ID NOT IN ( SELECT J.EMPLOYEE_ID FROM JOB_HISTORY J WHERE J.DEPARTMENT_ID = E.DEPARTMENT_ID ) 
	AND E.DEPARTMENT_ID IS NOT NULL 
GROUP BY
	E.DEPARTMENT_ID 
ORDER BY
	E.DEPARTMENT_ID;


SELECT
	E.EMPLOYEE_ID 
FROM
	EMPLOYEES E 
WHERE
	E.EMPLOYEE_ID IN ( SELECT J.EMPLOYEE_ID FROM JOB_HISTORY J WHERE J.DEPARTMENT_ID <> E.DEPARTMENT_ID) 
ORDER BY
	EMPLOYEE_ID;

SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME || ' ' || E.LAST_NAME FULLNAME,
	S.MINSAL,
	L.MAXSAL 
FROM
	EMPLOYEES E,
	( SELECT DEPARTMENT_ID, MIN( SALARY ) MINSAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID ) S,
	( SELECT DEPARTMENT_ID, MAX( SALARY ) MAXSAL FROM EMPLOYEES GROUP BY DEPARTMENT_ID ) L 
WHERE
	E.DEPARTMENT_ID = S.DEPARTMENT_ID 
	AND E.DEPARTMENT_ID = L.DEPARTMENT_ID;
	
SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME || ' ' || E.LAST_NAME FULLNAME,
	E.SALARY,
	( SELECT JOB_TITLE FROM JOBS WHERE JOB_ID = E.JOB_ID ) JOB_TITLE 
FROM
	EMPLOYEES E 
WHERE
	NOT EXISTS ( SELECT E2.EMPLOYEE_ID FROM EMPLOYEES E2 WHERE E2.JOB_ID = E.JOB_ID AND E2.SALARY > E.SALARY )
	ORDER BY EMPLOYEE_ID;
	
SELECT	
	DISTINCT JOB_ID,
	MAX(SALARY) MAX_SAL
FROM 
	EMPLOYEES
GROUP BY
	JOB_ID
	ORDER BY
	MAX_SAL DESC;
	
SELECT
	EMPLOYEE_ID 
FROM
	EMPLOYEES 
MINUS
SELECT DISTINCT
	MANAGER_ID 
FROM
	EMPLOYEES;
	
SELECT
	LOCATION_ID
FROM
	LOCATIONS
MINUS
SELECT
	LOCATION_ID
FROM 
	DEPARTMENTS;
	
	