SELECT JOB_ID, MAX(SALARY), MIN(SALARY), AVG(SALARY) FROM EMPLOYEES
GROUP BY JOB_ID ;

SELECT  DEPARTMENT_ID, COUNT(LAST_NAME) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ;

SELECT  DEPARTMENT_ID, COUNT(*) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ;

SELECT JOB_ID, MAX(SALARY), MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 80
GROUP BY JOB_ID ;

SELECT MANAGER_ID,COUNT(*)
FROM EMPLOYEES 
GROUP BY MANAGER_ID;

SELECT DEPARTMENT_ID,COUNT(*)
FROM EMPLOYEES
WHERE SALARY >= 3000
GROUP BY DEPARTMENT_ID; 

SELECT DEPARTMENT_ID,MIN(SALARY) MIN,MAX(SALARY) MAX,ROUND(AVG(SALARY),2) AVG 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID <> 80
ORDER BY AVG DESC,MAX DESC,MIN DESC;

SELECT DEPARTMENT_ID,ROUND(AVG(SALARY),4) "ABF"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING ROUND(AVG(SALARY),4) <= 7000;

SELECT (CEIL(SALARY/5000)-1)*5000||'K TO '||CEIL(SALARY/5000)*5000||'K' SALARY_GROUP , COUNT(*)
FROM EMPLOYEES
GROUP BY CEIL(SALARY/5000)
ORDER BY CEIL(SALARY/5000);

SELECT owner, table_name, column_name, data_type
FROM all_tab_columns
WHERE owner = 'HR';





