CREATE OR REPLACE TRIGGER NAME_CHECK 
BEFORE INSERT OR UPDATE OF STUDENT_NAME
ON STUDENTS
FOR EACH ROW 
DECLARE
I NUMBER;
CHR VARCHAR2(1);
BEGIN
	I := 1;
	WHILE(I <= LENGTH(:NEW.STUDENT_NAME))
	LOOP 
	CHR := SUBSTR(:NEW.STUDENT_NAME,I,1);
	IF NOT((CHR BETWEEN 'A' AND 'Z') OR (CHR BETWEEN 'a' AND 'z') OR CHR = ' ') THEN 
		RAISE_APPLICATION_ERROR(-20001,'INVALID NAME');
	END IF;
	I := I + 1;
	END LOOP;
END;
/